# Generated by Django 4.1.13 on 2024-09-08 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('url', models.URLField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_scan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('pin_image_url', models.URLField(null=True)),
                ('featured_image_url', models.URLField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_scan.site')),
            ],
        ),
    ]
