# Generated by Django 4.1.13 on 2024-09-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scan', '0002_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
