# Generated by Django 4.1.13 on 2024-11-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_scan', '0004_alter_site_created_on_alter_site_last_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinterestBoardSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=255)),
                ('board_name', models.CharField(max_length=255)),
                ('match_score', models.FloatField()),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_suggestions', to='site_scan.blogpost')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('blog_post', 'board_id')},
            },
        ),
    ]
