# Generated by Django 4.1.13 on 2024-09-08 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('pin_count', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('board_count', models.IntegerField(null=True)),
                ('pin_count', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('monthly_views', models.IntegerField(null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('access_token_expiration_dt', models.DateTimeField(null=True)),
                ('refresh_token_expiration_dt', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinterestPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('pin_count', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_publish.pinboard')),
            ],
        ),
    ]
